name: work
on: push
jobs:
    build-setup:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm install
            - run: |
                make setup

    test-lint:
        runs-on: ubuntu-latest
        needs: build-setup
        steps:
            - run: |
                make test
                make lint
